### ISSUE TITLE
Error when launching on a Debian 10 machine

### ISSUE THREAD

**Issue by dubicube** [securingdata/smartsafe-client-desktop#11]
Tried to launch the application on a Debian 10 machine, but  got the following error message:
```
$ java -jar SmartSafeClient-1.0.4.jar
Erreur : impossible de trouver ou de charger la classe principale fr.securingdata.smartsafe.LaunchView
Causé par : java.lang.NoClassDefFoundError: javafx/application/Application
```
I have the OpenJDK 11.0.11 installed. See more details below:

```
$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.11+9-post-Debian-1deb10u1, mixed mode, sharing)
```
Am I using a wrong Java version ? If so, it would be nice to precise it in the README. Thanks.

**Comment by securingdata** [comment]
SmartSafe is intended to work with Java 1.8. Preferred distribution: from Oracle.
Cross-platform is currently under testing.

**Comment by dubicube** [comment]
With Java 1.8 from Oracle, the client now runs.
But when I try to unlock a key, it gives me the error "No card reader detected", even if the key is plugged in.

**Comment by dubicube** [comment]
I installed **libccid** and **pcsc-tools** packages.
With the **pcsc_scan** command, I can see the token. But the smartsafe-client still does not see it.
Here is what I get with the **pcsc_scan** command:
```
$ pcsc_scan
Using reader plug'n play mechanism
Scanning present readers...
0: Gemalto USB Shell Token V2 (35C4D72C) 00 00
 
Sun Sep 12 12:32:14 2021
 Reader 0: Gemalto USB Shell Token V2 (35C4D72C) 00 00
  Event number: 0
  Card state: Card inserted, 
  ATR: 3B F7 18 00 00 80 31 FE 45 73 66 74 65 2D 6E 66 C4

ATR: 3B F7 18 00 00 80 31 FE 45 73 66 74 65 2D 6E 66 C4
+ TS = 3B --> Direct Convention
+ T0 = F7, Y(1): 1111, K: 7 (historical bytes)
  TA(1) = 18 --> Fi=372, Di=12, 31 cycles/ETU
    129032 bits/s at 4 MHz, fMax for Fi = 5 MHz => 161290 bits/s
  TB(1) = 00 --> VPP is not electrically connected
  TC(1) = 00 --> Extra guard time: 0
  TD(1) = 80 --> Y(i+1) = 1000, Protocol T = 0 
-----
  TD(2) = 31 --> Y(i+1) = 0011, Protocol T = 1 
-----
  TA(3) = FE --> IFSC: 254
  TB(3) = 45 --> Block Waiting Integer: 4 - Character Waiting Integer: 5
+ Historical bytes: 73 66 74 65 2D 6E 66
  Category indicator byte: 73 (proprietary format)
+ TCK = C4 (correct checksum)

Possibly identified card (using /usr/share/pcsc/smartcard_list.txt):
3B F7 18 00 00 80 31 FE 45 73 66 74 65 2D 6E 66 C4
	SmartCafe Expert 3.2 72K
```

**Comment by securingdata** [comment]
Thanks for these details. Investigation on-going.

**Comment by securingdata** [comment]
Should be fixed in v1.0.7
